version: '3.8'

services:
  db:
    image: 'postgres:13'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: atara
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: phonebook
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./config:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U atara"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    ports:
      - '8080:8080'
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgres://atara:mypassword@db:5432/phonebook

  tests:
    build: .
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgres://atara:mypassword@db:5432/phonebook
    command: go test ./tests

volumes:
  postgres_data: {}
